### ISSUE TITLE
Can't extract ota file

### ISSUE THREAD

**Issue by JohnMackYouTube05** [GooeyChickenman/victor#31]
When I run extract.py, (now that I have all the files downloaded)
It will extract the 4 files to the folder like normal. But it then tries to decrypt and extract the apq8009-robot-boot.img.gz file, and Python throws this error back at me:
`Decrypting apq8009-robot-boot.img.gz...
Traceback (most recent call last):
  File "C:\Users\liljm\Downloads\Vector-FIRM-BOOT-1.6.0.3331\extract.py", line 134, in <module>
    extract_encrypted_img(BOOT_IMG, arguments.output_directory)
  File "C:\Users\liljm\Downloads\Vector-FIRM-BOOT-1.6.0.3331\extract.py", line 100, in extract_encrypted_img
    working_dir
  File "C:\Users\liljm\Downloads\Vector-FIRM-BOOT-1.6.0.3331\extract.py", line 48, in decrypt
    stderr=subprocess.PIPE
  File "C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by rmcolbert** [comment]
The extract.py script isn't really intended to run on Windows.

**Comment by CozmoCyke** [comment]
With Windows , you could use this methods :

How to decrypt the OTA firmware files:



openssl enc -d -aes-256-ctr -pass file:ota.pas -in
apq8009-robot-boot.img.gz -out apq8009-robot-boot.img.dec.gz

openssl enc -d -aes-256-ctr -pass file:ota.pas -in
apq8009-robot-sysfs.img.gz -out apq8009-robot-sysfs.img.dec.gz





To use OpenSSL 1.1.0 or later, add “ -md md5” to the command:

openssl enc -d -aes-256-ctr -pass file:ota.pas -md md5 -in
apq8009-robot-boot.img.gz -out apq8009-robot-boot.img.dec.gz

openssl enc -d -aes-256-ctr -pass file:ota.pas -md md5 -in
apq8009-robot-sysfs.img.gz -out apq8009-robot-sysfs.img.dec.gz
